### ISSUE TITLE
configuration tweaks

### ISSUE THREAD

**Issue by JadeDaniel** [MarkE16/LaunchDarklyCLI#2]
If I don't put a token in, I get an unrecognized_token error but it doesn’t specify what key to set in the config file for access token. This would be more user friendly if it actually told me what key to use.

Also, do we need the configuration key in config.json?

**Comment by MarkE16** [comment]
I decided to put all the settings in `config.json` to have a simple way to get all those variables. In the future they can be accessed through environment variables since that would be better if this project does get big enough to work in workflows

**Comment by MarkE16** [comment]
Hi @JadeDaniel!

Been a while since I've been able to work on this project. Fortunately, I've been given access to my university's Linux servers, so now I should be able to pick up this project again and start making some progress. Going to have to refresh my knowledge of Bash to understand how everything works again but that's okay. Can't wait to continue on this project!

Speaking of which, I've re-written the `unrecognized_token` error to be more descriptive about what the issue was and how to potentially solve it by referencing the LD documentation on creating access tokens. (7aadb3c207584119b996b4acd2886b76dde7a72c)

Also, the token that I accidentally committed has been reset, so no worries about that.
